version: "4.12.0"

services:
  database:
    container_name: vial-backend-b
    image: postgres:latest
    environment:
      POSTGRES_USER: vial
      POSTGRES_PASSWORD: vial
      POSTGRES_DB: vial
    ports:
      - 5432:5432
  nodeserver:
    container_name: vial-backend-b-api
    image: node:22.14.0
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.local
    command: pnpm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - 8080:8080