FROM node:22 as development

# Install PNPM globally
RUN npm install -g pnpm

WORKDIR /usr/app

COPY ../.. .

RUN pnpm install

# Approve build scripts
RUN pnpm approve-builds --approve

RUN pnpm --filter backend prisma